title: Dion Thomas
position: Personal website and blog
description: Personal homepage, notes, and projects by Dion Thomas.
url: "https://dionthomas.nz"
baseurl: ""
lang: en-NZ

github_link: https://github.com/diont17
linkedin: https://www.linkedin.com/in/dion-thomas-352129203/
email: dion (at) wellumio.com

enable_footnote: true
show_excerpts: true

permalink: /blog/:year/:month/:day/:title/

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
  - scope:
      path: ""
    values:
      layout: page

exclude:
  - README.md

avatar: /assets/img/profile.jpg